"""The smallest useful custom rule."""

def _greeting_impl(ctx):
    """The implementation function. Runs during the ANALYSIS phase.

    It does NOT do work itself - it DECLARES actions that Bazel may run later,
    only if something actually needs the outputs.
    """

    # 1. Declare the output file. This creates a File object, not the file.
    out = ctx.actions.declare_file(ctx.label.name + ".txt")

    # 2. Register an action that will produce it.
    ctx.actions.write(
        output = out,
        content = "Hello, %s!\nGenerated by rule: %s\n" % (
            ctx.attr.who,
            ctx.label,
        ),
    )

    # 3. Return providers describing what this target offers to others.
    #    DefaultInfo.files is what `bazel build` on this target produces.
    return [DefaultInfo(files = depset([out]))]

greeting = rule(
    implementation = _greeting_impl,
    attrs = {
        "who": attr.string(
            default = "world",
            doc = "The name to greet.",
        ),
    },
    doc = "Writes a greeting file.",
)
