"""Generate signing keypairs in a repository rule, so no private key is committed.

A repository rule runs ONCE per workspace and its result is cached in the
output base. So the keys are stable for every build on this machine - which
keeps signatures reproducible locally - while never existing in git.

The tradeoff, stated plainly: signatures are NOT byte-identical across
machines, because each checkout generates its own keypair. For these examples
that is irrelevant (verification is what matters, not the signature bytes).
A real pipeline keeps the private key in a KMS/HSM and never generates one.
"""

def _signing_keys_impl(repository_ctx):
    openssl = repository_ctx.which("openssl")
    if openssl == None:
        fail("openssl not found on PATH; it is required by the signing examples")

    def run(args, what):
        result = repository_ctx.execute([str(openssl)] + args, timeout = 120)
        if result.return_code != 0:
            fail("openssl %s failed: %s" % (what, result.stderr))

    run(["genpkey", "-algorithm", "RSA", "-pkeyopt", "rsa_keygen_bits:2048",
         "-out", "rsa_private.pem"], "RSA keygen")
    run(["rsa", "-in", "rsa_private.pem", "-pubout", "-out", "rsa_public.pem"], "RSA pubout")
    run(["ecparam", "-name", "prime256v1", "-genkey", "-noout",
         "-out", "ec_private.pem"], "EC keygen")
    run(["ec", "-in", "ec_private.pem", "-pubout", "-out", "ec_public.pem"], "EC pubout")

    repository_ctx.file("BUILD.bazel", content = '''exports_files([
    "rsa_private.pem",
    "rsa_public.pem",
    "ec_private.pem",
    "ec_public.pem",
])

filegroup(
    name = "all_keys",
    srcs = glob(["*.pem"]),
    visibility = ["//visibility:public"],
)
''')

    repository_ctx.file("README.md", content = """# Generated test keys

Generated by //251_signing_basics:keys.bzl when this repository was fetched.
Never committed, never secret, never for production.
""")

signing_keys = repository_rule(
    implementation = _signing_keys_impl,
    doc = "Generates throwaway RSA and ECDSA keypairs for the signing examples.",
)
