load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

test_suite(
    name = "all_tests",
    tests = ["//100_capstone_composition/tests:store_test"],
)

pkg_tar(
    name = "dist",
    srcs = ["//100_capstone_composition/cli:tasks"],
    extension = "tar.gz",
    include_runfiles = True,
    package_dir = "/opt/tasks",
)
